name: Tests

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [master]

jobs:
  unit_tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        version: [1.22.4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - name: Run the cargo test
        run: go test ./...
